# Site settings
title: Johnny Ji
email: johnny@johnnyji.com
phone_number: 604-771-5528
description: > # this means to ignore newlines until "baseurl:"
  This is a collection of stuff that I found interesing and wanted to write about. Both as a coder and a human being in training.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://johnnyji.me" # the base hostname & protocol for your site
url: http://johnnyji.me
instagram: https://www.instagram.com/johnnyisji"
linkedin: https://www.linkedin.com/in/johnnyji
twitter: https://www.twitter.com/johnnyisji
github: https://www.github.com/johnnyji

# Build settings
markdown: kramdown
